#! /bin/bash

for jar in lib/*.jar; do export cp=$cp:$jar; done


ant wordnet &&

java -cp build:$cp -Xmx1g gov.llnl.ontology.wordnet.castanet.Autosummary ~/Projects/cs112/bin/like/cleaned data/bbc-sorted-stop-words.txt